[package]
name = "render_text_with_piston"
version = "0.1.0"
authors = ["zane <zane.a.karl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston_window = "0.120.0"
